### ISSUE TITLE
Bug: Alphaless

### ISSUE THREAD

**Issue by janIpen** [jwklong/omega-engine#7]
**Describe the bug**
When I click the gain alpha button with 1 alpha on a new save file, it will not give me any alpha
Also, if I click off the layers tab, the layer disappears

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new clean save file. DO NOT IMPORT!
2. Click on the gain alpha button twice.
3. You only have 1 alpha?!

1. Click off the layers tab (to settings).
2. Click back on the layers tab.

**Screenshots/Console log**
[Console log for no second alpha](https://hastebin.com/amajovoxas.properties)
[Console log for no alpha layer](https://hastebin.com/ciyirimari.properties)

**Device**
 - OS: windows 10
 - Browser: opera GX
 - Version: 1.0.0

**Comment by janIpen** [comment]
Add the major label when you see this

**Comment by jwklong** [comment]
fixed in v1.0.0 P1
